# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-10 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionInfo',
            fields=[
                ('file_name', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('func_name', models.CharField(max_length=1000)),
                ('func_param', models.CharField(blank=True, max_length=4000, null=True)),
                ('func_body', models.CharField(blank=True, max_length=10000, null=True)),
                ('func_line', models.CharField(blank=True, max_length=10000, null=True)),
            ],
            options={
                'verbose_name': 'Function detail',
                'verbose_name_plural': 'Function detail',
            },
        ),
    ]
