# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-10 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aynalize', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='functioninfo',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='functioninfo',
            name='file_name',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
