# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-12 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aynalize', '0003_auto_20190411_0842'),
    ]

    operations = [
        migrations.CreateModel(
            name='AynalizeStatus',
            fields=[
                ('update_time', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('process', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'aynalize status',
                'verbose_name_plural': 'aynalize status',
            },
        ),
    ]
